[package]
name = "usd"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4-sys = "1.9.4"
lz4_flex = "0.10.0"
nom = "7"
nom-derive = "0.10.1"
wasm-bindgen = "0.2.87"

[lib]
crate-type = ["cdylib", "rlib"]
